name: Pre-Release

on:
#  pull_request:
#    branches: [ develop ]
#    types: [closed]
  workflow_dispatch:

jobs:
  deploy:
    if: github.event.pull_request.merged || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all commits and tags

      - name: Get pre-release name
        id: pre-release-tag-name
        run: |
          # Fetch all tags
          git fetch --tags
          
          # Fetch last release
          last_release_tag=$(git tag -l '[0-9]*.[0-9]*.[0-9]*' --sort=-v:refname | head -n 1)
          
          # Fetch last pre-release
          last_pre_release_tag=$(git tag -l '[0-9]*.[0-9]*.[0-9]*-beta.*' --sort=-v:refname | head -n 1)
          
          if [ -z "$last_pre_release_tag" ]; then
            echo "No pre-release tags found"
            IFS='.' read -r release_major release_minor release_patch <<< "$last_release_tag"
            incremented_release_patch_number=$((release_patch + 1))
            new_pre_release_tag="$release_major.$release_minor.$incremented_release_patch_number-beta.1"
          else
            echo "Last pre-release tag: $last_pre_release_tag"
            IFS='.' read -r prerelease_major prerelease_minor prerelease_patch prerelease_beta_number <<< "$last_pre_release_tag"
            incremented_beta_number=$((prerelease_beta_number + 1))
            new_pre_release_tag="$prerelease_major.$prerelease_minor.$prerelease_patch.$incremented_beta_number"
          fi
          
#          echo "::set-output name=new_pre_release_tag::$new_pre_release_tag"
          echo "New pre-release tag is $new_pre_release_tag"
          echo "new_pre_release_tag=$new_pre_release_tag" >> $GITHUB_OUTPUT

      - name: Create pre-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          tag_name: ${{ steps.pre-release-tag-name.outputs.new_pre_release_tag }}
          release_name: ${{ steps.pre-release-tag-name.outputs.new_pre_release_tag }}
          prerelease: true
